name: accurity
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.0.1
  supabase_flutter: ^2.3.4
  connectivity_plus: ^5.0.2
  syncfusion_flutter_signaturepad: ^26.1.35
  http: ^1.1.0
  cached_network_image: ^3.3.0
  sentry_flutter: ^8.0.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
